---
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ nginx_package_name }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Deploy Nginx virtual host
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/ansible-lab.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Enable Ansible lab virtual host
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ansible-lab.conf
    dest: /etc/nginx/sites-enabled/ansible-lab.conf
    state: link
  notify: Reload nginx

- name: Disable default Nginx virtual host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Deploy application landing page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"

- name: Ensure Nginx is enabled and running
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: true
