---
nginx_package_name: nginx
nginx_service_name: nginx
nginx_server_name: "_"
nginx_listen_port: 80

app_name: "ansible-semaphore-lab"
app_environment: "production-lab"
app_message: "Hello from Ansible + Semaphore!"
